#lang racket

(provide prog)

;; example 0
;; numvar = 8
#;(define prog   '(let (a (lambda (x) x))
                (let (d 1)
                  (let (c (cons d d))
                    (let (f (apply a d))
                      (let (g 3)
                        (let (h (cdr c))
                          (let (i (apply a h))
                            (let (b (car c))
                              b)))))))))

;; example 1
;; numvar = 3
#;(define prog 
    '(let (a (lambda (x) x))
     (let (b 1)
       (let (c (apply a b))
         c))))

;; example 2
;; numvar = 8
(define prog
    '(let (a (lambda (j) j))
                (let (d 1)
                  (let (c (cons d d))
                    (let (f (apply a d))
                      (let (e 3)
                        (let (h (cdr c))
                          (let (i (apply a h))
                            (let (b (car c))
                              b)))))))))

;; example 3
;; numvar = 104
#;(define prog
  '(let (a (lambda (j) j))
     (let (b (lambda (j) j))
       (let (c (lambda (j) j))
         (let (d (lambda (j) j))
           (let (e (lambda (j) j))
             (let (f (lambda (j) j))
               (let (g (lambda (j) j))
                 (let (h (lambda (j) j))
                   (let (i (lambda (j) j))
                     (let (k (lambda (j) j))
                       (let (l (lambda (j) j))
                         (let (m (lambda (j) j))
                           
                           (let (n 1)
                             (let (o (apply a n))
                               (let (p (apply b o))  
                                 (let (q (apply c p))
                                   (let (r (apply d q))
                                     (let (s (apply e r))
                                       (let (t (apply f s))
                                         (let (u (apply g t))
                                           (let (v (apply h u))
                                             (let (w (apply i v))
                                               (let (x (apply k w))
                                                 (let (y (apply l x))
                                                   (let (z (apply m y))
                                                     (let (A (cons o p))
                                                       (let (B (cons q r))
                                                         (let (C (cons s t))
                                                           (let (D (cons u v))
                                                             (let (E (cons w x))
                                                               (let (F (cons y z))
                                                                 (let (G (cons o z))
                                                                   (let (H (cons p y))
                                                                     (let (I (cons q x))
                                                                       (let (J (cons r w))
                                                                         (let (K (cons s v))
                                                                           (let (L (cons t u))
                                                                             (let (M (car A))
                                                                               (let (N (car B))
                                                                                 (let (O (car C))
                                                                                   (let (P (car D))
                                                                                     (let (Q (car E))
                                                                                       (let (R (car F))
                                                                                         (let (S (cdr G))
                                                                                           (let (T (cdr H))
                                                                                             (let (U (cdr I))
                                                                                               (let (V (cdr J))
                                                                                                 (let (W (cdr K))
                                                                                                   (let (X (cdr L))
                                                                                                     (let (aa (lambda (j) j))
                                                                                                       (let (ab (lambda (j) j))
                                                                                                         (let (ac (lambda (j) j))
                                                                                                           (let (ad (lambda (j) j))
                                                                                                             (let (ae (lambda (j) j))
                                                                                                               (let (af (lambda (j) j))
                                                                                                                 (let (ag (lambda (j) j))
                                                                                                                   (let (ah (lambda (j) j))
                                                                                                                     (let (ai (lambda (j) j))
                                                                                                                       (let (ak (lambda (j) j))
                                                                                                                         (let (al (lambda (j) j))
                                                                                                                           (let (am (lambda (j) j))
                                                                                                                             
                                                                                                                             (let (an 1)
                                                                                                                               (let (ao (apply aa an))
                                                                                                                                 (let (ap (apply ab ao))  
                                                                                                                                   (let (aq (apply ac ap))
                                                                                                                                     (let (ar (apply ad aq))
                                                                                                                                       (let (as (apply ae ar))
                                                                                                                                         
                                                                                                                                         
                                                                                                                                         (let (at (apply af as))
                                                                                                                                           (let (au (apply ag at))
                                                                                                                                             
                                                                                                                                             
                                                                                                                                             (let (av (apply ah au))
                                                                                                                                               (let (aw (apply ai av))
                                                                                                                                                 (let (ax (apply ak aw))
                                                                                                                                                   (let (ay (apply al ax))
                                                                                                                                                     (let (az (apply am ay))
                                                                                                                                                       (let (aA (cons ao ap))
                                                                                                                                                         (let (aB (cons aq ar))
                                                                                                                                                           (let (aC (cons as at))
                                                                                                                                                             (let (aD (cons au av))
                                                                                                                                                               (let (aE (cons aw ax))
                                                                                                                                                                 (let (aF (cons ay az))
                                                                                                                                                                   (let (aG (cons ao az))
                                                                                                                                                                     (let (aH (cons ap ay))
                                                                                                                                                                       (let (aI (cons aq ax))
                                                                                                                                                                         (let (aJ (cons ar aw))
                                                                                                                                                                           (let (aK (cons as av))
                                                                                                                                                                             (let (aL (cons at au))
                                                                                                                                                                               (let (aM (car aA))
                                                                                                                                                                                 (let (aN (car aB))
                                                                                                                                                                                   (let (aO (car aC))
                                                                                                                                                                                     (let (aP (car aD))
                                                                                                                                                                                       (let (aQ (car aE))
                                                                                                                                                                                         (let (aR (car aF))
                                                                                                                                                                                           (let (aS (cdr aG))
                                                                                                                                                                                             (let (aT (cdr aH))
                                                                                                                                                                                               (let (aU (cdr aI))
                                                                                                                                                                                                 (let (aV (cdr aJ))
                                                                                                                                                                                                   (let (aW (cdr aK))
                                                                                                                                                                                                     (let (aX (cdr aL))
                                                                                                                                                                                                       aX)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
