# Add source files here
EXECUTABLE	:= sba-cuda
SHDOBJNAME	:= sba_cuda
# Cuda source files (compiled with cudacc)
CUBINFILES	:= gstm_driver.cu gstm_kernel.cu
OBJFILES	:= gstm_driver.o gstm_kernel.o

APPSRCFILES	:= gstm_common.cpp gstm_main.cpp
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= 

USEDRVAPI	:= 1
#lib to verify.
SOFILE	:=

include ../../../../sdk-ex/_common.mk
################################################################################
# Rules and targets

all:
	make clean
	#nvcc -o $(EXECUTABLE) -keep $(CUBINFILES) $(CCFILES) -I$(CUDASDKHOME)/common/inc -L. -L$(CUDALIB) -L$(CUDASDKHOME)/lib -L$(CUDASDKHOME)/common/lib/linux -lcuda -lcutil_$(LIB_ARCH) -lglut -arch sm_11
	nvcc --compiler-options '-fPIC' -o lib$(SHDOBJNAME).so -shared $(CUBINFILES) $(APPSRCFILES) -I$(CUDASDKHOME)/common/inc -L. -L$(CUDALIB) -L$(CUDASDKHOME)/lib -L$(CUDASDKHOME)/common/lib/linux -lcuda -lcutil_$(LIB_ARCH) -lglut -arch sm_11
	gcc -o $(EXECUTABLE) $(APPSRCFILES) -L. -l$(SHDOBJNAME) -I$(CUDASDKHOME)/common/inc -I$(CUDAHOME)/include
	mkdir data
	mv *.cubin data
	rm *.o *.cu.cpp *.hash *.i *.ii *.cudafe* *.gpu* *.fatbin* *.ptx

clean:
	rm -rf $(SOFILE) $(EXECUTABLE) data obj *.cu.cpp *.cubin *.hash *.i *.ii *.cudafe* *.gpu* *.fatbin* *.ptx *.cu.c *.so
