# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/skchoe/cuda-study/stasis/SBA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/skchoe/cuda-study/stasis/SBA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skchoe/cuda-study/stasis/SBA/CMakeFiles /home/skchoe/cuda-study/stasis/SBA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skchoe/cuda-study/stasis/SBA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sba

# Build rule for target.
sba: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sba
.PHONY : sba

# fast build rule for target.
sba/fast:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/build
.PHONY : sba/fast

#=============================================================================
# Target rules for targets named sba_prog

# Build rule for target.
sba_prog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sba_prog
.PHONY : sba_prog

# fast build rule for target.
sba_prog/fast:
	$(MAKE) -f CMakeFiles/sba_prog.dir/build.make CMakeFiles/sba_prog.dir/build
.PHONY : sba_prog/fast

driver.o: driver.c.o
.PHONY : driver.o

# target to build an object file
driver.c.o:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/driver.c.o
.PHONY : driver.c.o

driver.i: driver.c.i
.PHONY : driver.i

# target to preprocess a source file
driver.c.i:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/driver.c.i
.PHONY : driver.c.i

driver.s: driver.c.s
.PHONY : driver.s

# target to generate assembly for a file
driver.c.s:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/driver.c.s
.PHONY : driver.c.s

hashtab.o: hashtab.c.o
.PHONY : hashtab.o

# target to build an object file
hashtab.c.o:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/hashtab.c.o
.PHONY : hashtab.c.o

hashtab.i: hashtab.c.i
.PHONY : hashtab.i

# target to preprocess a source file
hashtab.c.i:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/hashtab.c.i
.PHONY : hashtab.c.i

hashtab.s: hashtab.c.s
.PHONY : hashtab.s

# target to generate assembly for a file
hashtab.c.s:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/hashtab.c.s
.PHONY : hashtab.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sba"
	@echo "... sba_prog"
	@echo "... driver.o"
	@echo "... driver.i"
	@echo "... driver.s"
	@echo "... hashtab.o"
	@echo "... hashtab.i"
	@echo "... hashtab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

