(let (cons-it (lambda (x) (let (r (cons x x)) r )))
  (let (t1 1)
    (let (pair1 (apply cons-it t1))
      (let (t2 t1)
        (let (pair2 (apply cons-it t2))
          (let (a (car pair2))
            (let (b (if a a t2)) b)))))))
